name: "clang-format"

on:
  push:
  pull_request:

jobs:
  check-format:
    name: "Run clang-format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Run clang-format"
        run: find . -regextype posix-extended -regex ".*\.(c|cpp|h|hpp)" | xargs -IX clang-format --Werror --dry-run X
